[package]
name = "pyke-diffusers"
version = "0.1.0"
rust-version = "1.62"
edition = "2021"
license = "Apache-2.0"
include = [
	"src/",
	"examples/",
	"scripts/",
	"clippy.toml",
	"LICENSE",
	"README.md",
	"requirements.txt",
	"rustfmt.toml"
]

[dependencies]
ndarray = { version = "0.15", features = [ "rayon" ] }
ndarray-rand = "0.14"
ndarray-stats = { version = "0.5", optional = true }
rayon = "1.5"
num-traits = "0.2"
anyhow = "1.0"
half = { version = "2.1", features = [ "num-traits" ] }
image = { version = "0.24", default-features = false, features = [ "png" ] }
rand = "0.8"
cfg-if = "1.0"

GSL = { version = "6.0", optional = true }
ort = { version = "1.13", default-features = false, features = [ "half" ] }

serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
tokenizers = { version = "0.13", optional = true, default-features = false, features = [ "onig" ] }

url = { version = "2.3", optional = true }
async-trait = { version = "0.1", optional = true }
crc32fast = { version = "1.3", optional = true }

ureq = { version = "2.5", optional = true, default-features = false, features = [ "tls", "json", "brotli" ] }
awc = { version = "3.0", optional = true, default-features = false, features = [ "rustls", "compress-brotli", "trust-dns" ] }
reqwest = { version = "0.11", optional = true, default-features = false, features = [ "rustls-tls", "brotli", "json" ] }
attohttpc = { version = "0.24", optional = true, default-features = false, features = [ "basic-auth", "compress", "json", "tls", "rustls" ] }

[dev-dependencies]
tokio = { version = "1.0", features = [ "full" ] }

[features]
default = [ "common-schedulers", "ort-copy-dylibs", "stable-diffusion" ]

tokenizers = [ "dep:tokenizers" ]

ort-cuda = [ "ort/cuda" ]
ort-copy-dylibs = [ "ort/copy-dylibs" ]

hub-ureq = [ "dep:ureq" ]
hub-awc = [ "dep:awc" ]
hub-reqwest = [ "dep:reqwest" ]
hub-attohttpc = [ "dep:attohttpc" ]
hub = [ "dep:url", "dep:async-trait", "dep:crc32fast" ]

scheduler-lms = [ "dep:GSL" ]
scheduler-ddim = []
scheduler-ddpm = []
scheduler-karras-ve = []
scheduler-pndm = []
scheduler-sde-ve = []
scheduler-sde-vp = []
scheduler-dpm-solver = [ "dep:ndarray-stats" ]
scheduler-euler = []
scheduler-euler-ancestral = []
scheduler-heun = []
common-schedulers = [
	"scheduler-ddim",
	"scheduler-ddpm",
	"scheduler-dpm-solver",
	"scheduler-euler",
	"scheduler-euler-ancestral"
]
all-schedulers = [
	"scheduler-lms",
	"scheduler-ddim",
	"scheduler-ddpm",
	"scheduler-karras-ve",
	"scheduler-pndm",
	"scheduler-sde-ve",
	"scheduler-sde-vp",
	"scheduler-dpm-solver",
	"scheduler-euler",
	"scheduler-euler-ancestral",
	"scheduler-heun"
]

stable-diffusion = [ "tokenizers" ]
safe-latent-diffusion = [ "tokenizers" ]
audio-diffusion = []

__why_is_rust_analyzer_like_this = []
