[package]
name = "pyke-diffusers"
version = "0.1.0"
rust-version = "1.62"
edition = "2021"
license = "Apache-2.0"

[[bin]]
name = "diffusers-reserialize-clip"
path = "scripts/reserialize_clip_tokenizer.rs"
required-features = [ "stable-diffusion", "serde", "serde_json" ]

[dependencies]
ndarray = { version = "0.15", features = [ "rayon" ] }
ndarray-rand = "0.14"
rayon = "1.5"
num-traits = "0.2"
anyhow = "1.0"
half = { version = "2.1", features = [ "num-traits" ] }
image = { version = "0.24", default-features = false, features = [ "png" ] }
rand = "0.8"
cfg-if = "1.0"
bitflags = "1.3"

GSL = { version = "6.0", optional = true }
ml2 = { git = "https://github.com/allie-project/ml2.git", optional = true, default-features = false, features = [ "half" ] }

ciborium = { version = "0.2", optional = true }
tokenizers = { version = "0.13", optional = true, default-features = false, features = [ "onig" ] }

url = { version = "2.3", optional = true }
serde = { version = "1.0", optional = true, features = [ "derive" ] }
serde_json = { version = "1.0", optional = true }
async-trait = { version = "0.1", optional = true }
crc32fast = { version = "1.3", optional = true }

ureq = { version = "2.5", optional = true, default-features = false, features = [ "tls", "json", "brotli" ] }
awc = { version = "3.0", optional = true, default-features = false, features = [ "rustls", "compress-brotli", "trust-dns" ] }
reqwest = { version = "0.11", optional = true, default-features = false, features = [ "rustls-tls", "brotli", "json" ] }
attohttpc = { version = "0.24", optional = true, default-features = false, features = [ "basic-auth", "compress", "json", "tls", "rustls" ] }

[dev-dependencies]
tokio = { version = "1.0", features = [ "full" ] }

[features]
default = [ "common-schedulers", "onnx", "stable-diffusion", "hub", "hub-reqwest" ]

onnx = [ "ml2", "ml2/onnx" ]
onnx-cuda = [ "ml2/onnxep-cuda" ]
onnx-copy-dylibs = [ "ml2/onnx-copy-dylibs" ]

hub-ureq = [ "dep:ureq" ]
hub-awc = [ "dep:awc" ]
hub-reqwest = [ "dep:reqwest" ]
hub-attohttpc = [ "dep:attohttpc" ]
hub = [ "dep:url", "dep:async-trait", "dep:crc32fast" ]

scheduler-lms = [ "dep:GSL" ]
scheduler-ddim = []
scheduler-ddpm = []
scheduler-karras-ve = []
scheduler-pndm = []
scheduler-sde-ve = []
scheduler-sde-vp = []
scheduler-dpm2 = []
scheduler-dpm2-ancestral = []
scheduler-euler = []
scheduler-euler-ancestral = []
scheduler-heun = []
common-schedulers = [
	"scheduler-ddim",
	"scheduler-ddpm",
	"scheduler-dpm2",
	"scheduler-dpm2-ancestral",
	"scheduler-euler",
	"scheduler-euler-ancestral"
]
all-schedulers = [
	"scheduler-lms",
	"scheduler-ddim",
	"scheduler-ddpm",
	"scheduler-karras-ve",
	"scheduler-pndm",
	"scheduler-sde-ve",
	"scheduler-sde-vp",
	"scheduler-dpm2",
	"scheduler-dpm2-ancestral",
	"scheduler-euler",
	"scheduler-euler-ancestral",
	"scheduler-heun"
]

stable-diffusion = [ "dep:ciborium", "dep:tokenizers" ]
safe-latent-diffusion = [ "dep:ciborium", "dep:tokenizers" ]
audio-diffusion = []

__why_is_rust_analyzer_like_this = []
